import {Player} from "@/models/player/player.model";


export const PLAYERS: Player[] = [
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  }
  ,{
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  }
  ,{
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  }
  ,{
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  }
  ,{
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  },
  {
    "id": 11,
    "firstName": "doica",
    "lastName": "viorel",
    "dateOfBirth": "10/20/3003",
    "cnp": "678912333",
    "birthNationality": "roman",
    "currentNationality": "roman",
    "phoneNumber": "noua incercare",
    "faxNumber": "7888",
    "email": "alba"
  }
]
